# -*- coding: utf-8 -*-
"""Expe7_AIDS-II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHA4aEv2b5pwq-7aMTKCJ70V9opIPoJF

**LY_IT_67 : Sakshi Salvi**

**- Experiment 7 : Implementation of Fuzzy Logic for suitable application**

Union
"""

A = dict()
B = dict()
Y = dict()

A = {"x": 0.4, "y": 0.8, "z": 0.1}
B = {"x": 0.6, "y": 0.5, "z": 0.9}

print('The First Fuzzy Set is :', A)
print('The Second Fuzzy Set is :', B)


for A_key, B_key in zip(A, B):
    A_value = A[A_key]
    B_value = B[B_key]

    Y[A_key] = max(A_value, B_value)

print('Fuzzy Set Union is :', Y)

"""Intersection"""

A = dict()
B = dict()
Y = dict()

A = {"x": 0.4, "y": 0.8, "z": 0.1}
B = {"x": 0.6, "y": 0.5, "z": 0.9}

print('The First Fuzzy Set is :', A)
print('The Second Fuzzy Set is :', B)


for A_key, B_key in zip(A, B):
    A_value = A[A_key]
    B_value = B[B_key]

    Y[A_key] = min(A_value, B_value)

print('Fuzzy Set Intersection is :', Y)

"""Complement"""

A = dict()
Y = dict()

A = {"x": 0.4, "y": 0.8, "z": 0.1}

print('The Fuzzy Set is :', A)


for A_key in A:
   Y[A_key]= 1-A[A_key]

print('Fuzzy Set Complement is :', Y)

"""Difference"""

A = dict()
B = dict()
Y = dict()

A = {"x": 0.4, "y": 0.8, "z": 0.1}
B = {"x": 0.6, "y": 0.5, "z": 0.9}

print('The First Fuzzy Set is :', A)
print('The Second Fuzzy Set is :', B)


for A_key, B_key in zip(A, B):
    A_value = A[A_key]
    B_value = B[B_key]
    B_value = 1 - B_value

    Y[A_key] = min(A_value, B_value)

print('Fuzzy Set Difference is :', Y)

"""Algebraic Sum"""

A = dict()
B = dict()
Y = dict()

A = {"x": 0.4, "y": 0.8, "z": 0.1}
B = {"x": 0.6, "y": 0.5, "z": 0.9}

print('The First Fuzzy Set is :', A)
print('The Second Fuzzy Set is :', B)


for A_key, B_key in zip(A, B):
    A_value = A[A_key]
    B_value = B[B_key]

    Y[A_key] = A_value + B_value - (A_value * B_value)

print('Fuzzy Set Algebraic Sum is :', Y)

"""Algebraic Product"""

A = dict()
B = dict()
Y = dict()

A = {"x": 0.4, "y": 0.8, "z": 0.1}
B = {"x": 0.6, "y": 0.5, "z": 0.9}
print('The First Fuzzy Set is :', A)
print('The Second Fuzzy Set is :', B)


for A_key, B_key in zip(A, B):
    A_value = A[A_key]
    B_value = B[B_key]

    Y[A_key] = (A_value * B_value)

print('Fuzzy Set Algebraic Product is :', Y)

"""Bounded Sum"""

A = dict()
B = dict()
Y = dict()
A = {"x": 0.4, "y": 0.8, "z": 0.1}
B = {"x": 0.6, "y": 0.5, "z": 0.9}

print('The First Fuzzy Set is :', A)
print('The Second Fuzzy Set is :', B)


for A_key, B_key in zip(A, B):
    A_value = A[A_key]
    B_value = B[B_key]

    Y[A_key] = min(1, (A_value + B_value))

print('Fuzzy Set Bounded Sum is :', Y)

"""Bounded Difference"""

A = dict()
B = dict()
Y = dict()

A = {"x": 0.4, "y": 0.8, "z": 0.1}
B = {"x": 0.6, "y": 0.5, "z": 0.9}

print('The First Fuzzy Set is :', A)
print('The Second Fuzzy Set is :', B)


for A_key, B_key in zip(A, B):
    A_value = A[A_key]
    B_value = B[B_key]

    Y[A_key] = max(0, (A_value - B_value))

print('Fuzzy Set Bounded Difference is :', Y)